### ISSUE TITLE
EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by misuqian** [indisoluble/AesGcm#10]
+ (void)getXorBuffer:(IAGUCharType *)buffer
          withBuffer:(IAGUCharType *)value1
              buffer:(IAGUCharType *)value2
          bufferSize:(IAGSizeType)bufferSize
{
    for (IAGSizeType i = 0; i < bufferSize; i++)
    {
        buffer[i] = (value1[i] ^ value2[i]); //EXC_BAD_ACCESS
    }
}

**Comment by indisoluble** [comment]
Hi @misuqian,

Thanks for your comment.

It is true that you might get a `EXC_BAD_ACCESS` here but only if `bufferSize` has the wrong value. Keep in mind that the file where this function is located: `IAGBitwiseComponents.h`, is not public; to be more precise, if you install this library as a **Pod**, only `IAGAesGcm.h`, `IAGCipheredData.h` & `IAGError.h` are accessible to an user. Check `AesGcm.podspec`, there you can see the following lines:

```
...
  s.source_files = 'AesGcm/Classes/**/*'
  s.public_header_files = 'AesGcm/Classes/*.h'
...
```

So there is not need for a validation here given that this method is only for internal use and `bufferSize ` will never have a wrong value.

Of course, if you think there is an input for the public interface that might cause this error, please let me know. I want to make this library as useful (and bug free) as possible :)

Regards.
