### ISSUE TITLE
Xcode 8.3+ nullability warnings

### ISSUE THREAD

**Issue by christophherrmann** [indisoluble/AesGcm#5]
In Xcode 8.3 and higher you get nullability warnings for `IAGBlockType` function parameters.

![aesgcm](https://cloud.githubusercontent.com/assets/10434774/25742225/cd37cf46-318e-11e7-96a0-baa87e06d8a9.png)

**Comment by indisoluble** [comment]
Fixed in pull request: https://github.com/indisoluble/AesGcm/pull/6
